### ISSUE TITLE
telegram bot update.

### ISSUE THREAD

**Issue by Robertnoob12** [pjamroziak/unsold-food-deals#29]
recently foodsi updated. and the api was moved somewhere else. try updating the bot so we can get notifitations if theres something available

**Comment by NickXDD** [comment]
Same problem here

**Comment by pjamroziak** [comment]
Project postponed until somebody discover a new endpoints

**Comment by Robertnoob12** [comment]
the problem is, i saw someone saying that theres the old api with restaurants which makes it harder...

**Comment by Robertnoob12** [comment]
host seems to be control.kochava.com fiddler files
[foodsi.zip](https://github.com/pjamroziak/unsold-food-deals/files/12680240/foodsi.zip)

**Comment by Robertnoob12** [comment]
@pjamroziak maybe u can look in the fiddler files on pc. And find where it goes
